SUBELEMENTS = "subelements"
DESCRIPTION = "desc"
ID = "id"
TYPE = "type"
FAILURE_RATE = "failure_rate"
K = "k"

BASIC_EVENT = "BasicEvent"
EXTERNAL_EVENT = "ExternalEvent"
AND_GATE = "ANDGate"
OR_GATE = "ORGate"
NAND_GATE = "NANDGate"
NOR_GATE = "NORGate"
KN_GATE = "KNGate"
